---

- hosts: all
  sudo: True

  vars:
    app_name: ranko
    repo_url: https://github.com/cloverfeed/ranko.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv/webapps
    wsgi_callable: app
    wsgi_file: wsgi.py
    server_name: ranko.emillon.org
    dbname: ranko
    dbuser: ranko
    app_config_file: conf/production.py
    secret_environment: ""

  roles:
    - role: appserver
    - role: dbserver
