language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
    - "pip install sphinx --use-mirrors"
    - "pip install sphinxcontrib-httpdomain --use-mirrors"
before_install:
    - npm install coffee-script
before_script:
    - npm install casperjs
    - export PATH=node_modules/phantomjs/bin:node_modules/casperjs/bin:$PATH
    - python run.py &
script:
    - nosetests --with-coverage --cover-package=app
    - casperjs test tests.coffee
    - make -C docs html
notifications:
    slack: cloverfeed:Zd60W6QoaC1pGFP85rOvNJa1
after_success:
    coveralls
