language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
    - "pip install sphinx --use-mirrors"
    - "pip install sphinxcontrib-httpdomain --use-mirrors"
before_install:
    - npm install coffee-script
script:
    - nosetests --with-coverage --cover-package=app
    - make -C docs html
notifications:
    slack: cloverfeed:Zd60W6QoaC1pGFP85rOvNJa1
after_success:
    coveralls
