language: python
sudo: false
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
    - "pip install sphinx --use-mirrors"
    - "pip install sphinxcontrib-httpdomain --use-mirrors"
before_install:
    - npm install coffee-script
before_script:
    - npm install casperjs
    - npm install grunt-cli
    - npm install grunt
    - npm install grunt-contrib-jasmine
    - npm install grunt-template-jasmine-istanbul
    - python manage.py assets build
    - export PATH=node_modules/phantomjs/bin:node_modules/casperjs/bin:$PATH
    - python manage.py -c conf/development.py create
    - python run.py &
script:
    - nosetests --with-coverage --cover-package=app
    - grunt
    - casperjs test tests.coffee
    - make -C docs html
notifications:
    slack: cloverfeed:Zd60W6QoaC1pGFP85rOvNJa1
after_success:
    coveralls
deploy:
    provider: heroku
    api_key:
        secure: Yj7sDPQnWhUENr45/+gkf3c8dCwE8or91GIXWbln9HrZUAXwaO8o7Rkhd/tUTLmQWJxkrCSAsGahen8t00/gVwhIawrIl/vnOx2e5YIkH8eVFtutfMcegM8GW8LFGYGceIQoWshYHgCltG4myhMtK2omswQ55ky61W0bhBaQDvg=
    app: ranko
    on:
        repo: cloverfeed/ranko
