import os

SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
LOG_EXCEPTIONS = os.getenv('LOG_EXCEPTIONS')
LOG_TO_STDERR = os.getenv('LOG_TO_STDERR')
SLACK_API_TOKEN = os.getenv('SLACK_API_TOKEN')
SLACK_CHANNEL = os.getenv('SLACK_CHANNEL')
SLACK_USERNAME = os.getenv('SLACK_USERNAME')
SLACK_ICON_URL = os.getenv('SLACK_ICON_URL')
