"""Add Document.filetype

Revision ID: 22608a4a8a06
Revises: 3a4d84aee44c
Create Date: 2014-11-05 10:44:33.931694

"""

# revision identifiers, used by Alembic.
revision = '22608a4a8a06'
down_revision = '3a4d84aee44c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('filetype', sa.String(), nullable=False, server_default='pdf'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'filetype')
    ### end Alembic commands ###
