"""Add Annotation.user

Revision ID: 30c88af31d58
Revises: 4e32faff090b
Create Date: 2014-10-30 15:36:08.588860

"""

# revision identifiers, used by Alembic.
revision = '30c88af31d58'
down_revision = '4e32faff090b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('user', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'user')
    ### end Alembic commands ###
