"""Add User.only_doc_id

Revision ID: 35e1dcbfdf30
Revises: 4e474383082f
Create Date: 2014-12-18 15:15:19.349578

"""

# revision identifiers, used by Alembic.
revision = '35e1dcbfdf30'
down_revision = '4e474383082f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('only_doc_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'only_doc_id')
    ### end Alembic commands ###
