"""Add Document.title

Revision ID: 3706a29a80c6
Revises: 4d7c99d11827
Create Date: 2014-12-15 15:11:30.030681

"""

# revision identifiers, used by Alembic.
revision = '3706a29a80c6'
down_revision = '4d7c99d11827'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'title')
    ### end Alembic commands ###
