"""Add Annotation.state

Revision ID: 3a4d84aee44c
Revises: 30c88af31d58
Create Date: 2014-10-31 10:44:00.373036

"""

# revision identifiers, used by Alembic.
revision = '3a4d84aee44c'
down_revision = '30c88af31d58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('state',
                                          sa.SmallInteger(),
                                          nullable=False,
                                          server_default='0',
                                          ))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'state')
    ### end Alembic commands ###
