"""Add Document.user_id

Revision ID: 4d7c99d11827
Revises: 51a83463dbb6
Create Date: 2014-11-19 15:30:59.036558

"""

# revision identifiers, used by Alembic.
revision = '4d7c99d11827'
down_revision = '51a83463dbb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'user_id')
    ### end Alembic commands ###
